name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
      - name: Install the project dependencies
        run: poetry install
      - run: poetry run ruff check
      - run: poetry run ruff format --check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
      - name: Install the project dependencies
        run: poetry install
      - run: poetry run mypy kition_djangodefaults

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - uses: actions/setup-python@v5
        with:
          cache: "poetry"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install the project dependencies
        run: poetry install
      - run: poetry run python -m unittest